// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyizvlxOdlxunVhn6BmYV0CB9UgNQMlZY',
    appId: '1:737612668977:android:7ba18756d8aa714d0eb510',
    messagingSenderId: '737612668977',
    projectId: 'whilabel',
    databaseURL: 'https://whilabel-default-rtdb.firebaseio.com',
    storageBucket: 'whilabel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCvAuomQcgoHFnjOPEiJ0y7JondVQuNg',
    appId: '1:737612668977:ios:39608ec615e819220eb510',
    messagingSenderId: '737612668977',
    projectId: 'whilabel',
    databaseURL: 'https://whilabel-default-rtdb.firebaseio.com',
    storageBucket: 'whilabel.appspot.com',
    androidClientId: '737612668977-0hb3jljbg2gc38mm7gjibfklps7ivv97.apps.googleusercontent.com',
    iosClientId: '737612668977-pv1gtftu42hflra2qh8i9jiv46anmerr.apps.googleusercontent.com',
    iosBundleId: 'com.earningRight.whilabel',
  );
}
